---
title: "R Notebook"
output: html_notebook
---
install data manipulator package
```{r}
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("gridExtra")
```
Loading core library
```{r}
#Load core tidyverse package
library(tidyverse)
library(ggplot2)
library(grid)
library(gridExtra)
```

Titanic EDA


read data
data set is store under data directory
```{r}
dataset <- read.csv(file = "../data/train.csv")
```

let's explore our dataset
```{r}

glimpse(dataset)

```




```{r}
type <- c("int","int","int","chr","chr","dbl","int","int","chr","dbl","chr","chr")
description <- c("Passenger identification number","is Survived","Ticket Class","Passenger Name","Sex","Age in years","No. of sibling / spouses aboard the Tinatic","No. of parents, children aboard the Titanic","Ticket Number","Passenger fare","Cabin number","Port of Embarkation")
Key <- c("","0 = NO, 1= YES ","","","","","","","","","","")
meta_data <- matrix(c(colnames(dataset),type,description,Key),nrow= 12, ncol=4)
meta_data 

```
```{r}
colnames(meta_data) <- c("Features","Data Type","Definition","Key")
grid.newpage()
grid.table(meta_data)
```


column list
- Survived 
- Pclass




from the summary, we could see that from survived variable 
